# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: covigator-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::vafator=0.3.3