name: Integration tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get --assume-yes install gcc gfortran build-essential wget libfreetype6-dev libpng-dev libopenblas-dev
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install virtualenv
    - name: Install vafator
      run: |
        python setup.py bdist_wheel
        pip install dist/*
    - name: Run integration tests
      run: |
        make clean integration_tests