name: Workflow tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: defaults,conda-forge,bioconda
    - name: Install dependencies
      run: |
        apt-get update
        apt-get --assume-yes install wget make procps software-properties-common
        apt-get --assume-yes install build-essential libcurl4-openssl-dev libz-dev liblzma-dev
        wget -qO- https://get.nextflow.io | bash && cp nextflow /usr/local/bin/nextflow
        python -m pip install --upgrade pip
        pip install setuptools wheel
        # this is needed by cyvcf2 and pysam
        conda install htslib=1.14
    - name: Install vafator
      run: |
        python setup.py bdist_wheel
        pip install dist/*
    - name: Run tests
      run: |
        make clean workflow_tests